apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: site-management
spec:
  template:
    metadata:
      name: site-management-v1
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: docker.io/toannv6895/site-management